name: Simple workflow for test
run-name: ${{ github.actor }} launched this workflow!
on:
  pull_request:
    branches: 
      - dev
  push:
    branches:
      - main
jobs:
  Say-Hello-And-Goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "Saying Hello"
        run: |
          echo "Hello Workflow"
          echo "Second command"
      - name: "Saying Goodbye"
        run: echo "GoodBye"
      - name: "Creating a file"
        run: touch file.iut
      - name: "Check file creation"
        run: ls -l
      - name: "Writing into file..."
        run: echo "Un mot..." > file.iut
      - name: "Reading file..."
        run: |
          cat file.iut
          more file.iut
          less file.iut
          nl file.iut
          head file.iut
  Second-Job:
    runs-on: ubuntu-latest
    needs: Say-Hello-And-Goodbye
    steps:
      - name: "Checking files..."
        run: ls -l
