name: Simple workflow for test
run-name: ${{ github.actor }} launched this workflow!
on: [push]
jobs:
  Say-Hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Workflow"
      - run: echo "Running on $RUNNER_OS"
