name: Simple workflow for test
run-name: ${{ github.actor }} launched this workflow!
on: [push]
jobs:
  Say-Hello-And-Goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "Saying Hello"
        run: |
          echo "Hello Workflow"
          echo "Second command"
      - name: "Saying Goodbye"
        run: echo "GoodBye"
      - name: "Creating a file"
        run: touch file.iut
      - name: "Check file creation"
        run: ls -l
